// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function fizzbuzz(number) {
  var match = number % 3;
  var match$1 = number % 5;
  if (match !== 0) {
    if (match$1 !== 0) {
      return String(number);
    } else {
      return "buzz";
    }
  } else if (match$1 !== 0) {
    return "fizz";
  } else {
    return "fizzbuzz";
  }
}

exports.fizzbuzz = fizzbuzz;
/* No side effect */
